// import "./sidebar/visit.cy"

import "./tasks/helpers/get_sub_tree_ids.cy"
import "./tasks/collapse.cy"
import "./tasks/create_new_task.cy"
import "./tasks/delete.cy"
import "./tasks/focusing.cy"
import "./tasks/markDone.cy"
import "./tasks/moving.cy"
import "./tasks/IndividualTask/specifing_task.cy"
import "./tasks/subtasks.cy"
import "./tasks/visit_tasks.cy.ts"
